version: '3.3'
services:
  pent_quest_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "epzp"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "test"
    ports:
      - 3306:3306
    volumes:
      - "database:/var/lib/mysql"
      - "./orginal_data:/home/dump/"
    networks:
      - pent_quest_db_network

networks:
  pent_quest_db_network:
    driver: bridge


volumes:
  database:
    external: false