FROM php:8.1.3-fpm

RUN apt-get update
RUN apt-get install -y --no-install-recommends libfreetype6-dev libjpeg62-turbo-dev libpng-dev 

RUN docker-php-ext-configure gd  --with-jpeg=/usr/include/ --with-freetype=/usr/include/
RUN docker-php-ext-install -j$(nproc) gd

RUN apt-get update
RUN docker-php-ext-install bcmath
RUN apt-get install git -y
RUN apt-get install mariadb-client -y

RUN set -eux; 
#RUN apt-get install php-xml -y;
RUN apt install zlib1g-dev && apt-get install zlib1g;
RUN apt-get install cmake libfreetype6-dev libfontconfig1-dev xclip -y;
RUN apt update;
RUN	apt-get install \
		coreutils \
#		freetype2 \
		libjpeg-dev \
		libpng-dev \
		libzip-dev \
# postgresql-dev is needed for https://bugs.alpinelinux.org/issues/3642
	-y ; 

RUN	docker-php-ext-configure gd \
 		--enable-gd \
		--with-freetype \
		--with-jpeg=/usr/include \
	; 

RUN	docker-php-ext-install \
		opcache \
		pdo_mysql \
		zip; 

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/

RUN apt install nginx -y
    COPY ./docker/nginx/conf.d /etc/nginx/conf.d


RUN apt install wget \
		gnupg \
		lsb-release -y
# RUN wget http://repo.mysql.com/mysql-apt-config_0.8.22-1_all.deb
#RUN dpkg -i mysql-apt-config_0.8.22-1_all.deb
#RUN apt update
# RUN apt install mysql-server
# RUN wget https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-server_8.0.29-1ubuntu21.10_amd64.deb-bundle.tar
# RUN tar -xf mysql-server_8.0.29-1ubuntu21.10_amd64.deb-bundle.tar  -C /tmp
# RUN apt install libc6 \
# 			libstdc++6 \
# 			-y

# RUN apt install /tmp/mysql-community-server-core_8.0.29-1ubuntu21.10_amd64.deb

RUN apt install vim -y
RUN apt install htop -y



RUN mkdir -p /var/www/html/web/sites/default/files 
RUN	chmod -R 765 /var/www/html/ 
RUN	chown -R www-data:www-data /var/www/html 
RUN	chmod -R 777 /var/www/html/web/sites/default 
RUN	cd /var/www/html/web/sites/default 
# RUN	cp ./default.settings.php /var/www/html/web/sites/default/settings.php 
# RUN	chmod -R 777 /var/www/html/web/sites/default/settings.php



# RUN ls;
#RUN chown -R www-data /var/www/html/web/sites/default



COPY . /app

