<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;


function format_uri( $string, $separator = '_' ) {
  $accents_regex = '~&([a-z]{1,2})(?:acute|cedil|circ|grave|lig|orn|ring|slash|th|tilde|uml);~i';
  $special_cases = array( '&' => 'and', "'" => '');
  $string = mb_strtolower( trim( $string ), 'UTF-8' );
  $string = str_replace( array_keys($special_cases), array_values( $special_cases), $string );
  $string = preg_replace( $accents_regex, '$1', htmlentities( $string, ENT_QUOTES, 'UTF-8' ) );
  $string = preg_replace("/[^a-z0-9]/u", "$separator", $string);
  $string = preg_replace("/[$separator]+/u", "$separator", $string);
  return $string;
}

function dms($message){
  \Drupal::messenger()->addStatus($message);
}


/**
 * Implements hook_theme().
 */
function pentacomp_main_theme($existing, $type, $theme, $path) {
  return [
    'pentacomp_admin_token' => [
      'render element' => 'form',
      'template' => 'form/pentacomp_admin_token'
    ],
    'pentacomp_token_gen' => [
      'render element' => 'form',
      'template' => 'form/pentacomp_token_gen'
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pentacomp_main_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'pentacomp_main_user_login_form_submit';
}

/**
 * Custom submit handler for the login form.
 */
function pentacomp_main_user_login_form_submit($form, FormStateInterface $form_state) {
  $roles = \Drupal::currentUser()->getRoles();
  if(in_array('questionnaire_moderator', $roles)) {
    $url = Url::fromRoute('pentacomp_main.token.generator');
    $form_state->setRedirectUrl($url);
  } else if(in_array('editor', $roles)) {
    $url = Url::fromRoute('<front>');
    $form_state->setRedirectUrl($url);
  }
}

/**
 * Implements hook_preprocess_page().
 */
function pentacomp_main_preprocess_page(array &$variables) {
	$current_route = \Drupal::routeMatch();		
	$route_name = $current_route->getRouteName();
  if ($route_name == 'pentacomp_main.token.generator') {
  //  echo '<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>aaaa';
  //  $variables['#attached']['library'][] = 'pentacomp_main/pentacomp_main.form.generator';
  }
}
